### ISSUE TITLE
Build Scenario 2: 2.2 & 2.3 - RDP Authentication 

### ISSUE THREAD

**Issue by Andu1391** [marianleica/azrez#13]
Scenario 2 - Create a basic Azure VM = Windows 11 & Windows Server 2022
Deployment - ok 
RDP to VM - Initial Error due to not being connected to my azure account, fixed with connect-azacoount, as suggested by the script. 
Subsequent deployment, while trying to RDP it failed to authenticate me multiple times via fingerprint/pin and would not connect. 

Workaround: Used the provided unique password to RDP manually.
Q: How to recover the initial unique password? As after the RDP prompt, the PS window closes.

https://github.com/user-attachments/assets/0b8460e0-8b9d-4d73-abf3-14816d642a65

**Comment by marianleica** [comment]
[like]  Marian Leica reacted to your message:
________________________________
From: Andu1391 ***@***.***>
Sent: Friday, November 1, 2024 3:29:31 PM
To: marianleica/azrez ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [marianleica/azrez] Create a basic Azure VM - Windows 11 & Windows Server 2022 - RDP Authentication (Issue #13)


Scenario 2 - Create a basic Azure VM = Windows 11 & Windows Server 2022
Deployment - ok
RDP to VM - Initial Error due to not being connected to my azure account, fixed with connect-azacoount, as suggested by the script.
Subsequent deployment, while trying to RDP it failed to authenticate me multiple times via fingerprint/pin and would not connect.

Workaround: Used the provided unique password to RDP manually.
Q: How to recover the initial unique password? As after the RDP prompt, the PS window closes.

https://github.com/user-attachments/assets/0b8460e0-8b9d-4d73-abf3-14816d642a65

**Comment by marianleica** [comment]
The RDP auth session should be with the provided credentials at the end, so in your case -> More choices -> Username and password

as given by
```
Write-Output "The public IP address allocated to VM ${VM} is ${vmip}"
Write-Output "The admin user name is: azrez"
Write-Output "The unique password is: ${randompass}"
```

The session should wait for user input before closing in the `"Press any key to continue..."` prompt

Though valid concern is however how to get back to these credentials once you exited.

Implementing a logs output for this scenario. Thanks for the help!
Should in all VM cases be there by 1.06 next week
